#####################################################
# Dieses Docker Compose file enthaelt drei Server
#    Sonar Server
#     - sonar-db
#     - sonar-backend
#     - sonar-frontend
#    MQTT Server
#    Herne Server
#####################################################

services:

  ### Server Sonar ###
  sonar-db:
    image: postgres:13.1-alpine
    container_name: sonar-db
    env_file:
      - .env/db-credentials.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - sonar-net
    restart: unless-stopped


  sonar-backend:
    build:
      context: ./sonar-backend
      dockerfile: Dockerfile
    depends_on:
      sonar-db:
        condition: service_healthy
    container_name: sonar-backend
    env_file:
      - .env/sonar-backend-credentials.env
    environment:
      MQTT_SERVER_URI: "tcp://mqtt-broker:1883"
    ports:
      - "8081:8081"
    networks:
      - sonar-net
      - mqtt-net
    restart: unless-stopped


  sonar-frontend:
    build:
      context: ./sonar-frontend
      dockerfile: Dockerfile
    depends_on:
      - sonar-backend
    container_name: sonar-frontend
    ports:
      - "8080:80"
    networks:
      - sonar-net
    restart: unless-stopped



  ### Server MQTT Broker ###
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt-net
    restart: unless-stopped



  ### Server Herne ###
  herne-backend:
    build:
      context: ./herne-backend
      dockerfile: Dockerfile
    container_name: herne-backend
    ports:
      - "9091:8080"
    environment:
      MQTT_SERVER_URI: "tcp://mqtt-broker:1883"
    networks:
      - herne-net
      - mqtt-net
    restart: unless-stopped



networks:
  sonar-net:
  mqtt-net:
  herne-net:

volumes:
  sonar_db_data: