spring.application.name=sonar
# der port, auf dem das backend startet
server.port=8081

# url zum datenbank container -> siehe docker-compose.yaml
spring.datasource.url=jdbc:postgresql://sonar-db:5432/sonar
# username und passwort aus umbegunsvariablen
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# methode, mit der die datenbank gestartet wird -> create-drop: beim start wird table gedropped
spring.jpa.hibernate.ddl-auto=create-drop
