spring.application.name=sonar-backend
# der port, auf dem das backend startet
server.port=8081

# url zum datenbank container -> siehe docker-compose.yaml
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sonar}
# username und passwort aus umbegunsvariablen
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# methode, mit der die datenbank gestartet wird -> create-drop: beim start wird table gedropped
spring.jpa.hibernate.ddl-auto=create-drop

# Explizite Spezifikation des Hibernate Dialekts
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Required for MQTT communication
mqtt.server.uri=${MQTT_SERVER_URI:tcp://localhost:1883}
mqtt.communication.timeout.millis=50000

# Logging
logging.level.root=INFO

# CORS (Cross-Origin Resource Sharing) Allowed Origin is a mechanism that allows a server to specify which origins are allowed to access its resources.
cors.allowed.origin.sonar.frontend.url=${CORS_ALLOWED_ORIGINS_SONAR_FRONTEND_URL:http://localhost:3000,http://localhost:8080}